### ISSUE TITLE
Undefined index: post_type in debug mode

### ISSUE THREAD

**Issue by Dweez** [advancedforms/advanced-forms#13]
Hello,

First, thanks for your plugin, it's a huge time saver

However, in debug mode, I have errors of this type:

`NOTICE: wp-content/plugins/advanced-forms/acf/acf-additions.php:116 - Undefined index: post_type`

I'm on php7 with ACF pro 5.6.1 and AF 1.3.2

Thank you for your work !
dweez

**Comment by asitemade4u** [comment]
Hi, I had exactly the same error, reported it to Acf this morning. My hunch is that it could come from a website installed into a folder.

**Comment by Dweez** [comment]
> My hunch is that it could come from a website installed into a folder.

In my case it's a root install

**Comment by Fabianlindfors** [comment]
This has been fixed with 7ecf0273046e724a5e7ea61371a948650828fe83.

Sorry about the delay and thanks for pointing it out! Big thanks to Triloworld for creating a PR!
