### ISSUE TITLE
Bundling within plugin?

### ISSUE THREAD

**Issue by bebaps** [advancedforms/advanced-forms#19]
Thanks for your work with this plugin, it works very well and easy easy to set up.

Similar to Advanced Custom Fields, are there hooks in place to allow a developer to bundle your plugin within our own? The plugin I am building will only be used internally within my organization, but I do not trust the other admins not to poke around and disable your plugin on accident.

Thanks!

**Comment by Fabianlindfors** [comment]
Oh, this is something I have wanted to add but I haven't gotten around to it!

I'm thinking some simple instructions for including AF with a plugin/theme and then a filter for hiding the admin parts? Are you aiming to define all your forms with PHP?

**Comment by bebaps** [comment]
Thanks for the reply. Yes, currently I am doing everything within PHP, so to your point in the back end there is just an empty Forms area. Of course I know the cause of this, but another admin may see this and disable the plugin thinking that it has no effect on the site.

<img width="274" alt="screen shot 2017-10-30 at 7 39 22 pm" src="https://user-images.githubusercontent.com/5995907/32205059-434e01d0-bdaa-11e7-85d5-863f0d5aa76e.png">

**Comment by Fabianlindfors** [comment]
I've added a few new hooks with commit 6dd8f92a1a34780eaa8da51528336859db05efae. These should be enough to properly include AF in a plugin or theme. The changes will be included in the next release, until then you can grab the latest version from Github!

The first is a filter called `af/settings/show_admin`. Hook into it and return false to hide AF from the admin panel completely.

There are also two more which might not be necessary for you but I would still recommend overriding them. The filter `af/settings/path` should provide the file system path to your AF installation. The filter `af/settings/url` should provide the base URL path to the AF installation.

These are very similar to the ones ACF has and are used in basically the same way: [https://www.advancedcustomfields.com/resources/including-acf-in-a-plugin-theme/](https://www.advancedcustomfields.com/resources/including-acf-in-a-plugin-theme/)

**Comment by bebaps** [comment]
Thank you for implementing this. I will utilize these hooks soon!
