### ISSUE TITLE
Form output is not returned

### ISSUE THREAD

**Issue by LachlanArthur** [advancedforms/advanced-forms#2]
When using the `advanced_form` function ([docs](https://advancedforms.github.io/guides/basic/displaying-a-form/)) with `"echo" => false`, the form output does not get returned.

**Comment by Fabianlindfors** [comment]
You're totally right!

I just pushed a commit to the develop branch with a quick fix. Thanks a lot for creating this issue!

559b90e26e99502b271b8afa161c8df110e35f89
