### ISSUE TITLE
If show admin filter set to false no fields are registered.

### ISSUE THREAD

**Issue by Wemago** [advancedforms/advanced-forms#22]
I was looking at your code, haven't debugged yet, but the way you have coded the show admin filter to not include the admin files will make that the fields aren't also registered, so if you are using AF programmatically you won't have access to the fields, or am I wrong?

BTW, nice coding!

**Comment by Fabianlindfors** [comment]
Oh, good point!

I thought I was making some clever performance savings but this might become an issue. I changed it back with commit a2a4104. Thanks a ton for pointing it out!
