### ISSUE TITLE
Possibility to submit form in ajax

### ISSUE THREAD

**Issue by codep0et** [advancedforms/advanced-forms#24]
Hello, great plugin. Very helpful.

I was wondering if there was a possibility to have the form submit in AJAX and receive the success message and show it ?

Instead of having the form reload.

Thank you

**Comment by Fabianlindfors** [comment]
Hi! I'm sorry about my late response.

Currently there isn't a way to submit through AJAX but it's definitely something I would like to add eventually.

Hope you're enjoying Advanced Forms despite this!

**Comment by codep0et** [comment]
Hi. No problem. 

It would indeed be a nice feature. If I have a moment I'll try to work on it and submit a PR to help out

Great plugin. Love the concept of making it work with ACF

**Comment by drwhoooois** [comment]
@fabianlindfors 
just wanted to know if you are planning to add this any time soon? thanks

**Comment by fabianlindfors** [comment]
Hi!

Currently this is still in the backlog and there are no plans to add it in the near future. :)
