### ISSUE TITLE
Issue with "Duplicate Post"

### ISSUE THREAD

**Issue by DamChtlv** [advancedforms/advanced-forms#25]
Hi,

I realised today that if you use the plugin "Duplicate post" to make multiple copy of a form, it works almost fine (form id is changed), but, there might be some hidden fields that still contain information / formID of the original form (when i fill a copy of the form and send it, it register the entries and use settings of the original form instead).

**Comment by Fabianlindfors** [comment]
Hi! Sorry I'm replying so late to this.

I hadn't tried Duplicate post with AF before but I just did and it worked for me. I just a custom generated form key to identify all forms and this needs to be unique. When duplicating a form a new form key should be generated for the duplicated form which works as expected for me. So does the entries.

Could you check if your duplicated form has a different form key from the original? Thanks!

**Comment by fabianlindfors** [comment]
I'll close this for now. Please re-open if you have any more details. :)
