### ISSUE TITLE
Taxonomies - multi-select field 

### ISSUE THREAD

**Issue by silentFred** [advancedforms/advanced-forms#26]
Hey there,

Just checking in if taxonomy multi-select works? I can't seem to get it right. Using checkbox works just fine, not multiselect though. I'm using advanced_form with basic args.

Cheers for now =)

**Comment by Fabianlindfors** [comment]
Hi! I just tested this in my local environment and it worked for me.

Could you be more specific about what kind of issues you are experiencing?
Thank!

**Comment by fabianlindfors** [comment]
I'll close this for now. Please re-open if you have more details. :)

**Comment by silentFred** [comment]
Thanks @fabianlindfors! I reverted back to 1.3.5 and it sorted the image field issue we are discussing in the WP forum =)
