### ISSUE TITLE
Notice: Undefined index: type

### ISSUE THREAD

**Issue by scrobbleme** [advancedforms/advanced-forms#30]
Hello,

when enabled, we get the folling warning, which brokes some funtionality.

`Notice: Undefined index: type in /XYZ/wp-content/plugins/advanced-custom-fields-pro/includes/api/api-field.php on line 1812`

This happens with:

- PHP 7.0
- WordPress 4.9.5
- ACF Pro 5.6.10
- Advanced Forms 1.3.5
- Twenty Seventen Theme

**Comment by Fabianlindfors** [comment]
Hi!

Does this issue persist after deactivating Advanced Forms? Are there any other plugins enabled on the site?

Thanks!

**Comment by scrobbleme** [comment]
No,

it is only there, when Advanced Forms is activated.

There are no other plugins, only what is defined avove:

WordPress 4.9.5
ACF Pro 5.6.10
Advanced Forms 1.3.5
Twenty Seventen Theme

**Comment by scrobbleme** [comment]
Strange, my version of ACF Pro was not correctly uploaded, but no error with this. After uploading it again, everything worked. Sorry for any inconvenience.
