### ISSUE TITLE
Not working with Divi builder

### ISSUE THREAD

**Issue by scrobbleme** [advancedforms/advanced-forms#34]
Hello,

as soon as we add an advanced form to the content using Divi builder, it is not possible to edit the page anymore (backend editor).

The basic problem seems to be, that jQuery isn't loaded anymore.

![image](https://user-images.githubusercontent.com/504835/40975516-86ab3750-68cb-11e8-8d2a-dd669aabdb91.png)

**Comment by fabianlindfors** [comment]
Hi!
If I remember correctly I had a different user experiencing the same problem with Divi builder. I believe it's connected to how conditional logic is handled by ACF and my plugin which causes jQuery to be included early.

There are some good news though. ACF 5.7 contains a rewrite of conditional logic which fixes the issues I've been experiencing which I also think are causing your issues. If you upgrade to ACF 5.7 (release candidate available from the website) and grab the latest version of AF here from Github it might solve your problem. Could you try that?

Thanks!

**Comment by scrobbleme** [comment]
Finally working with ACF 5.7 ;)
