### ISSUE TITLE
Nested groups not displayed in e-mail notification

### ISSUE THREAD

**Issue by oduska** [advancedforms/advanced-forms#36]
It seems groups inside of groups don't display their values in e-mails.

Top screenshot is from an e-mail test:

![nested-groups](https://user-images.githubusercontent.com/18633943/41305804-4ddb7bea-6e31-11e8-81c4-d66da20d1f3b.png)

**Comment by fabianlindfors** [comment]
Hi!

This seems to have been a bug and I've fixed it with commit b88a57b4cb41861816280e9f679b3f45ec300c09. Will be included in the next release!

Thanks for bringing this to my attention. :)
