### ISSUE TITLE
Question: Older releases

### ISSUE THREAD

**Issue by silentFred** [advancedforms/advanced-forms#41]
Hi there,

Is it possible to retrieve older releases somewhere? 

Kind regards,

**Comment by fabianlindfors** [comment]
Absolutely!
They are available from wordpress.org. Go here: https://wordpress.org/plugins/advanced-forms/advanced/ and scroll to the bottom. Select a version, click download and you're good to go!

**Comment by fabianlindfors** [comment]
Hello again! I've fixed this issue now and will soon release 1.5.2 with the fix. :)
Until then the fix is available here on Github with commit 073d96b6e2a6521e2cf50685a940c53be4c4d0db. Hope this helps!
