### ISSUE TITLE
Feature request: Make submit button text editable &/ translatable

### ISSUE THREAD

**Issue by Jaska** [advancedforms/advanced-forms#43]
Maybe the display section could have an input field for the submit button?

Also, I'm not sure if text such as "Validation failed. 2 fields require attention" are from ACF or AF but these strings should be easily changed and or translated.

Thanks!

**Comment by fabianlindfors** [comment]
Hi! Sorry about the late reply to your issue.

There is an argument that can be used to change the submit button text. Check out the documentation for more info: https://advancedforms.github.io/guides/basic/displaying-a-form/

The validation failure text probably comes from ACF and should be translatable through there!
