### ISSUE TITLE
ACF is not defined

### ISSUE THREAD

**Issue by jethromay** [advancedforms/advanced-forms#47]
Hi,

The current way i'm displaying my form is by using: <?php advanced_form( 'FORM_ID' ); ?>

The form works and i receive my email however when using this i get the following console error: "ACF is not defined."

![acf](https://user-images.githubusercontent.com/6702147/47289266-2b4ff200-d5fa-11e8-854e-2b65c9140352.png)

**Comment by fabianlindfors** [comment]
Hi! Sorry about the late reply to your issue.

Are you still experiencing this problem? Please re-open the ticket and I'll give you a hand!
