### ISSUE TITLE
af_register_email action

### ISSUE THREAD

**Issue by ajuliano** [advancedforms/advanced-forms#52]
I want to add email programmatically, just like it's possible to do with af_register_form. But I can't find a similar simple way to do it. For now I use af/form/submission and wp_mail(). But is there a way to do it with any af_ filter/action?

Thanks!

**Comment by fabianlindfors** [comment]
Hi!

My plugin has a built-in export-to-code function which lets you generate PHP code for registering a form you've set up in the admin interface. I would create the form through the WordPress admin with email notifications and then use the export functionality to generate the registration code. When editing a form there should be an "Export" button on the right side of the page!

Hope this helps!
