### ISSUE TITLE
Gallery Field not working when not logged in as Admin  - "Cannot read property 'query' of undefined"

### ISSUE THREAD

**Issue by MPHood** [advancedforms/advanced-forms#55]
Hey guys.

I´ve got a gallery field in my Form. When I´m logged in to Wordpress (as Admin) everything works fine.

But as a regular (logged in User /non Admin) the "Upload Button" for the Gallery does not work (when its klicked, it does not open the browser to choose the images,) - If I check the console, I get the following error message:

Uncaught TypeError: Cannot read property 'query' of undefined
    at i.addFrameStates (acf-input.min.js?ver=5.7.13:3)
    at initialize (acf-input.min.js?ver=5.7.13:3)
    at i.t (acf-input.min.js?ver=5.7.13:1)
    at i.acf.Model (acf-input.min.js?ver=5.7.13:1)
    at i [as constructor] (acf-input.min.js?ver=5.7.13:1)
    at new i (acf-input.min.js?ver=5.7.13:1)
    at Object.acf.newMediaPopup (acf-input.min.js?ver=5.7.13:3)
    at i.onClickAdd (acf-pro-input.min.js?ver=5.7.13:1)
    at i.<anonymous> (acf-input.min.js?ver=5.7.13:1)
    at HTMLAnchorElement.d (jquery.js?ver=1.12.4:2)

I just bought your Plugin today, an put much hope in it - I hope you can help.

Thanks

**Comment by fabianlindfors** [comment]
Hi again!

The problem here is that the ACF gallery field is dependent on the WordPress media uploader, and the uploader doesn't work if no user is logged in. This is really unfortunate but also a bit unavoidable.
I would recommend replacing the gallery field with a repeater of image fields. Not quite as nice but still a pretty good user experience.

Hope this works!

**Comment by MPHood** [comment]
The User is logged in  - But as Subscriber. 
It only works as admin.

**Comment by fabianlindfors** [comment]
Yes, sorry! It’s dependent on the permissions on the current user, subscribers by default don’t have permissions to manage media. It might work to add these permissions but I haven’t tried this myself. Check this out for example: https://www.wordpresscircle.com/how-to-allow-contributor-and-subscriber-to-upload-images-via-media-library/

Are you certain that WP User Frontend uses ACF for its gallery field? I can’t seem to find any info indicating so.

**Comment by MPHood** [comment]
You can try it for yourself: https://fyt24.com/profil-anlegen - > The fifth field i called "gallery" -> maps the images to the acf gallery field (the Images get uploaded without using the wp media uploader -> You can choose an upload images right from your computer= - It works for subscribers too, not only for admins.

**Comment by MPHood** [comment]
Short Update: If I use a Plugin to give the Subscribers the permisson to upload images - the gallery works.

But now also the regular Image-Upload fields (for featured image ...) open the media library when the upload button is clicked. (Before changeging the permissions, it opened my desktop browser to upload directy) -> I dont want this Userrole to have Access to the Media library.   

As I said in WPUF you can upload multiple images to the gallery directly from desktop with any Userrole.

**Comment by fabianlindfors** [comment]
I'm guessing that WPUF is using their own field types and hence could add their own gallery field which the maps to the ACF one. I'm trying to not re-implement ACF functionality and especially leave all field related functionality to ACF itself.

Regarding the regular file upload you can set the "uploader" argument to "basic" to avoid the WordPress media uploader. There is a bit of info in the documentation: https://advancedforms.github.io/guides/basic/displaying-a-form/
