### ISSUE TITLE
Make Form-Submissions pending

### ISSUE THREAD

**Issue by MPHood** [advancedforms/advanced-forms#56]
Hey Guys - Me again.

How can I change the post status of a form submission to "pending" ?

**Comment by fabianlindfors** [comment]
Hi!

This can be done with a tiny bit of code. Something like this should work:

```
function create_post_as_draft() {
    // Set post status as draft
    $post_data['post_status'] = 'draft';

    return $post_data;
}
add_filter( 'af/form/editing/post_data/key=FORM_KEY', 'create_post_as_draft');
```

Just replace FORM_KEY with your form key. :) You're not the first to ask about so I'll be including this as part of the admin interface in the next release. Stay tuned!

**Comment by jessor** [comment]
For anyone copy-pasting the snippet above, it's missing `$post_data` in the function declaration:

```php
function create_post_as_draft( $post_data ) {

    $post_data['post_status'] = 'draft';
    return $post_data;
}

add_filter( 'af/form/editing/post_data/key=FORM_KEY', 'create_post_as_draft' );
```

**Comment by fabianlindfors** [comment]
Thanks @jessor! Also it's worth noting that this snippet is no longer needed. You can set the post status through the form settings now!
