### ISSUE TITLE
Preventing spam

### ISSUE THREAD

**Issue by rcobiella** [advancedforms/advanced-forms#58]
Hi everyone, 

I've been experiencing a considerable amount of spam coming from forms using the plugin. It's a bit of a problem for my customers, so I'm trying to figure out what's the best way to handle this without adding a captcha field, which is not optimal for smaller forms like quick newsletter sign-up, where the captcha would be bigger than the form itself.

ACF forms do have an option to add a honeypot field to avoid this. Is there any way of implementing this using Advanced Forms as well? I can add a hidden field myself to do this, but it would be great to have an option to do it automatically, or maybe even to be able to use native ACF forms options as well as the AF ones.

Thanks!

**Comment by fabianlindfors** [comment]
Hi!

I actually have a fully working honeypot implementation which will be included in the upcoming release. I took the opportunity to push it to Github just now, you can find the changes in commit 21dcbe048b676f995ad1eeb8fa290bdadb17375f.

I would be very grateful if you could download a copy here from Github and try out the honeypot. It should be enabled by default!

**Comment by rcobiella** [comment]
Just tried it and it works perfectly. Thanks a lot, that was fast!

Is there a pro version of this? My only problem now is that I'm missing the settings menu, which I really need :)

**Comment by fabianlindfors** [comment]
Sure! If you reach out through here: https://hookturn.io/contact/ I'll send over a Pro copy :)
