### ISSUE TITLE
Adding template to outgoing emails

### ISSUE THREAD

**Issue by rcobiella** [advancedforms/advanced-forms#59]
Hi again,

I'm wondering if there's a way to edit the mail content before it's sent to add a template. I'm able to modify the array content with af/email/before_send, but the changes aren't showing. I see them if I use var_dump, but not in the emails.

What's the best way to do this?

Thanks.

**Comment by fabianlindfors** [comment]
Hi, Rafa!

There sure is a way. The `af/form/email/content` filter will let you edit the mail content before it's sent. More info here: https://advancedforms.github.io/filters/af-form-email-content/
