### ISSUE TITLE
Calculated Field not Showing in Email Notification

### ISSUE THREAD

**Issue by MPHood** [advancedforms/advanced-forms#60]
Hey guys!

The value of the calculated field ist showing in the email notification template after submitting a form.

The other fields work perfectly fine and can be viewed in the email.

am I missing something?

**Comment by fabianlindfors** [comment]
Hi!

Sorry to say that calculated fields are currently not supported in success messages or email notifications. I realize now that I have not made this clear at all and I just updated the documentation to reflect this.

With that being said I would really like to add support for this and I think I have an idea on how to achieve it. Would you like to beta test this feature?

**Comment by MPHood** [comment]
Hey. Of course i would like to do a beta test.

How do we proceed?

**Comment by fabianlindfors** [comment]
Nice!

Please reach out to me by clicking "contact me" here: fabianlindfors.se. Hopefully I can have something for you to test acceptably soon.

**Comment by MPHood** [comment]
Fixed with the latest Update: :)
