### ISSUE TITLE
session_start(): Cannot start session when headers already sent

### ISSUE THREAD

**Issue by kolyasapphire** [advancedforms/advanced-forms#61]
Hi! After enabling debug log I noticed warning level entries for:

https://github.com/advancedforms/advanced-forms/blob/36f795a886d3db53ca0740d4ba836f585b56e7b5/api/api-submissions.php#L30

`session_start(): Cannot start session when headers already sent`

These happen on /wp-cron.php cron requests.

PHP 7.3.7, WordPress 5.2.2, ACF Pro 5.8.2, Advanced Forms 1.6.4

**Comment by kolyasapphire** [comment]
It seems that solution on Wordpress.org support solves this issue:

Changing the if statement to:
`if( !headers_sent() && '' == session_id() ) {`

Source:
https://wordpress.org/support/topic/php-warnings-cannot-start-session-when-headers-already-sent/

**Comment by fabianlindfors** [comment]
Hi! Thanks for giving more information on this. Does it only happen during requests to wp-cron.php?

Unfortunately the fix from the forums will be overridden when a new update is released. I'm very eager to fix it though so any help is highly appreciated!

**Comment by fabianlindfors** [comment]
@CalebBarnes Sorry about the late reply. This might actually be fixed now. Could you try installing the plugin from Github and see if the issue persists?

**Comment by kolyasapphire** [comment]
Hi @fabianlindfors somehow missed your message, sorry! Updated to 1.6.5, Sentry caught the error again

**Comment by CalebBarnes** [comment]
It seems to just be triggered by a spider thousands of times so its not terrible for the end user but its annoying because it eats up my sentry quota.

**Comment by kolyasapphire** [comment]
I also received an error recently for line 41:

https://github.com/advancedforms/advanced-forms/blob/01bf2c97e2768738c43c1efbeb96f915a82880dc/api/api-submissions.php#L41

**Comment by fabianlindfors** [comment]
Hi!

I just pushed d320ec2abcf88da111d3ea5ddfcd04a06e5275eb which changes the way my plugin handles submission sessions. It no longer relies on PHP sessions and these warnings should be a thing of the past in the next version.

If you could update from Github and test it out I'd be really grateful! :)

**Comment by kolyasapphire** [comment]
Updated with these changes, will report if I spot any errors, thanks a lot!
