### ISSUE TITLE
Mailchimp sign-up checkbox

### ISSUE THREAD

**Issue by rcobiella** [advancedforms/advanced-forms#63]
Hello!

I've been looking for similar related issue but I couldn't find any, so here I go.

Is there any way to add a checkbox in a form so it does the Mailchimp sign-up only if it's checked? I'm trying to incorporate a newsletter sign-up check in a larger form to avoid having 2 separate ones, but I can't find anything in the documentation.

I could always have a hidden Mailchimp embedded form that's auto-filled with the main form data and submitted via ajax, but it feels a bit sketchy to do it this way.

Thank you,
Rafa

**Comment by fabianlindfors** [comment]
Hi!

There isn't an obvious way but there is a way. The `af/form/mailchimp/request` filter can be used to edit the API request before it's sent to Mailchimp. By returning false from this you could stop the sign up. Something like this:

```
function conditional_mailchimp_signup( $request ) {
  $sign_up = af_get_field( 'CHECKBOX_FIELD_NAME' );
  if ( !$sign_up ) {
    return false;
  }

  return $request; 
}
add_filter( 'af/form/mailchimp/request/key=FORM_KEY', 'conditional_mailchimp_signup', 10, 1 );
```

**Comment by rcobiella** [comment]
Thanks! I'll try this.

And sorry about the delay, I totally missed the notification!
