### ISSUE TITLE
Email Notfications dont work for fields that are inside a "ACF-Group Field" 

### ISSUE THREAD

**Issue by MPHood** [advancedforms/advanced-forms#65]
After long work of styling my form by using the acf-group fields i discovered that all the fields that are inside an acf-group field dont work with email notifications.

**Comment by fabianlindfors** [comment]
Hi!

You're right that `{all_fields}` doesn't support group fields at the moment. Hope to correct this in the future. You can still include every subfield individually by doing `{field:field_name[sub_field_name]}`.

**Comment by MPHood** [comment]
Hi thanks for your quick response! You´re right - it was my mistake, i used {field:field_name}, so it did not work. 

Anyway thank you very much for making it clear
