### ISSUE TITLE
Custom form validation not working

### ISSUE THREAD

**Issue by drwhoooois** [advancedforms/advanced-forms#70]
this documentation 
https://advancedforms.github.io/actions/af-form-validate/

does not work
what is form id and where do you get that id?
add_action( 'af/form/validate/id=FORM_ID', 'validate_form', 10, 2 );

**Comment by fabianlindfors** [comment]
Hi!

`FORM_ID` is the post ID in WordPress of your form. I would generally recommend using the `FORM_KEY` alternative instead. You can find your form key right beneath the title when editing a form.
