### ISSUE TITLE
Feature Request: Reply to in emails

### ISSUE THREAD

**Issue by drwhoooois** [advancedforms/advanced-forms#71]
can you please add the option where we can specify reply-to email?

example: 
![image](https://user-images.githubusercontent.com/50954304/67731387-608ddd80-f9ce-11e9-982a-e1ce34399e94.png)

when we get the notification and we hit reply, it should reply to the person who sent the message

**Comment by fabianlindfors** [comment]
Hi!

I would recommend using the email header filter for this. It's really easy to use:https://advancedforms.github.io/filters/af-form-email-headers/.
