### ISSUE TITLE
Feature Request: display option for entries 

### ISSUE THREAD

**Issue by drwhoooois** [advancedforms/advanced-forms#72]
Right now entries show post title, form and date. It would be great if we had the option to select fields from the form and display instead. 

![image](https://user-images.githubusercontent.com/50954304/67731568-0e00f100-f9cf-11e9-9f3c-5556cc74a542.png)

user is able to check what fields are to be shown for entries

**Comment by fabianlindfors** [comment]
Hi!

Are you referring to the list columns in the admin panel?
