### ISSUE TITLE
Feature Request: Conditional email notifications

### ISSUE THREAD

**Issue by drwhoooois** [advancedforms/advanced-forms#73]
It would be great if we could setup conditional fields for email notifications. 
Send email if field  is ....
or 
Send email if field is 

example: 
![image](https://user-images.githubusercontent.com/50954304/67731940-2de4e480-f9d0-11e9-9bc6-3e08f120f63c.png)

**Comment by fabianlindfors** [comment]
Hi!

This is a very good idea and something that is also on the roadmap for the integrations in the Pro plugin. Thank you!
