### ISSUE TITLE
Uploader does not validate for non-logged in users

### ISSUE THREAD

**Issue by drwhoooois** [advancedforms/advanced-forms#74]
If you create a file field and set a limit to file size, you can still upload the file and submit it but it doesnt store it anywhere

**Comment by hacknug** [comment]
@drwhoooois did you find any way to work around the issue?

**Comment by fabianlindfors** [comment]
Hi, @hacknug!

I'm currently working on improving support for the basic uploader and hopefully fixing this issue. Would you be willing to test it out for me?

**Comment by fabianlindfors** [comment]
Great! I just pushed these changes to Github, please download the plugin from here. Let me take a moment to explain what I have done.

This change is server-side and not client-side. It will stop any submissions with invalid uploads but it will not provide for a good user experience. If an upload is invalid then the user will be shown an error message on a new page which is inconsistent with how other validation works.

The reason for this is that ACF does not support client-side validations of file uploads in the general case. I've been trying to implement this myself but unfortunately I haven't yet found a way. I recommend you implement it manually for your form using the ACF JS API: https://www.advancedcustomfields.com/resources/javascript-api/.
