### ISSUE TITLE
Ordering ACF Field Groups

### ISSUE THREAD

**Issue by asitemade4u** [advancedforms/advanced-forms#8]
Hi Fabian,
Thank you for your OUTSTANDING work that really saved my day yesterday, and today and for the next days to come too ;o))
There are several things I would like possible on the plugin, notably the Ordering of ACF group fields in the form.
Here is the context:

1.  I have several ACF group fields used for the same Custom Post Type (CPT). For example, for a **People CPT**: Personal info, Postal address, Communication means
2. The same for my Advanced Form > I have allocated all these ACF groups to the same form
3. But I cannot figure out on **how to order them within the form** -- they seem to retain the order of ACF, neither the order of creation, nor the alphabetical order.

Thank you!
Stephen

**Comment by Fabianlindfors** [comment]
Hi! I'm glad to hear Advanced Forms is working well for you.

The order of the field groups is determined entirely by ACF which has a custom system for ordering.  In the settings of your field groups there should be a "Order no." field which you can edit (lower order numbers appear first). The order you set using this field should carry over to AF.

Here's what it looks like on the field group edit page:

<img width="1207" alt="skarmavbild 2017-04-14 kl 21 56 59" src="https://cloud.githubusercontent.com/assets/4345277/25054468/91121666-215d-11e7-834a-d1edb492430c.png">

**Comment by asitemade4u** [comment]
OMG, of course...
Thank you for your help!
