### ISSUE TITLE
When using Easy SMTP plugin, the notification email addresses are always overrided by specified server mail

### ISSUE THREAD

**Issue by Jaska** [advancedforms/advanced-forms#84]
I'm not sure whether this is a problem with Advanced Forms or Easy SMTP.

But I have notifications setup so that the email "from" field is the field the user fills. This way it is easy to just reply to a contact form. 
But for some reason, this email address is overrided. Easy SMTP plugin has a setting that seems to address this exact situation but it doesn't seem to work.

Can you help?

![image](https://user-images.githubusercontent.com/1336032/79534069-44682080-8082-11ea-81f9-537b21152ebe.png)

**Comment by Jaska** [comment]
The problem was with Easy WP SMTP but it is now fixed (v1.3.9.3).

**Comment by fabianlindfors** [comment]
Great! :)
