### ISSUE TITLE
Form will not send if multiple addresses are added

### ISSUE THREAD

**Issue by geeworthington** [advancedforms/advanced-forms#86]
If the "custom recipient" field has multiple addresses added, the form will no longer send.... It will submit and the entries will be added into the database (if enabled) , but the actual email will not send.

A fix for this - albeit temporary, is to remove multiple recipients and only have one.

This previously did work but has broken somewhere along with line with an update.

Tested on;
- WP 5.5
- ACF Pro 5.8.13
- Advanced Forms 1.6.9

**Comment by fabianlindfors** [comment]
Hi!

I looked into this and you're right, there was a regression in 1.6.9 causing comma-separated recipients to no longer work. I've now fixed the issue and pushed to Github. Could you try installing the plugin from here and see if that fixes your issue? Thanks!

**Comment by geeworthington** [comment]
@fabianlindfors @fabian-tigerton  

This is working fine now.

Sorry for the delayed response.

Thank you! 

- [x] You are a boss

**Comment by fabianlindfors** [comment]
Nice to hear! :)
