### ISSUE TITLE
Writing ACF field values into a new custom post

### ISSUE THREAD

**Issue by asitemade4u** [advancedforms/advanced-forms#9]
Hi Fabian,
Another question: what do you recommend when adding a new CPT from AdvancedForms, re the **ACF field input when one validates the form**?

[In the manual](https://advancedforms.github.io/guides/advanced/setting-up-a-form-to-create-posts/) you describe updating the Title and Content of the newly created post.
But what about ACF fields? [ACF Documentation](https://www.advancedcustomfields.com/resources/update_field/) states that:
> This example demonstrates how to achieve the same as above using the field’s key instead of it’s name. The field’s key should be used when saving a new value to a post (when no value exists). This helps ACF create the correct ‘reference’ between the value and the field’s settings.

If it is correct, it makes it VERY awkward to update a field because now we are dealing with TWO field references: the name (which is natural) and the Field Key.

Please tell me your thoughts.
Stephen

**Comment by Fabianlindfors** [comment]
I would recommend following the ACF recommendations to ensure the field values work as intended. Advanced Forms currently doesn't provide any special way of saving the custom field values and is totally reliant upon ACF functions.

It's definitely cumbersome and a shortcoming of ACFs design. I have an idea of adding a helper function to AF which let's you transfer a submitted form value to it's matching field with a single function call. This way I could make it possible to use field names without any downsides. Unfortunately this is just an idea and not currently part of the plugin.

Thanks for asking! Feel free to create another issue if you have other questions or suggestions. :)

**Comment by asitemade4u** [comment]
Thanks Fabian, I understand your point and encourage you to build this helper function.
I think your plugin has a real potential and should be included into ACF ;o)) 
I wrote a review yesterday.
Take care!
Stephen

**Comment by Fabianlindfors** [comment]
Thanks for the review, truly appreciated!

I thought about your problem a bit more and decided I should probably implement a helper function right now. It's such a common use case for AF that it should be streamlined.

I just pushed commit 0de97638c7bf173448b3d3728ae9e6ccdb12c984 with a new helper function `af_save_field_to_post`. It takes the field key or name plus a post ID and saves the submitted field value directly to the post. I have already put it in use for AFs automatically generated entries!

Thanks a lot for bringing the issue up! Will submit a new version (1.1.1) to the plugin directory soon.

**Comment by asitemade4u** [comment]
WOW, so nice of you!!!
Have you ever thought of using Advanced Forms with the CLONE field from ACF?
It transforms it into another wonderland... Of course, I can explain.

**Comment by Fabianlindfors** [comment]
I haven't, no, but I'd love to expore it.

Feel free to explain if you have the time. I'm very interested!

**Comment by asitemade4u** [comment]
Sent you a private email on the topic, did not want to clutter this page...
