### ISSUE TITLE
Upload file in form, restriction not apply

### ISSUE THREAD

**Issue by cedricDevWP** [advancedforms/advanced-forms#94]
I create a form with a upload file. I added a restriction on allowed file types (.jpg, .pdf...) but when i submit if i add a .csv the restriction wasn't apply on ajax

It's normal ?

**Comment by fabianlindfors** [comment]
Hi! This is unfortunately a bug in ACF which remains unfixed. It also affects ´acf_form()`. I would recommend reaching out to ACF support and put some pressure on them to fix the issue :)

**Comment by cedricDevWP** [comment]
OK i will do that
