### ISSUE TITLE
ACF not defined in wp-admin

### ISSUE THREAD

**Issue by DimitrijRees** [advancedforms/advanced-forms#97]
Just noticed a JS console error in wp-admin on all websites where we're using ACF and AF:

Uncaught ReferenceError: acf is not defined

Thrown in:

acf.addAction('new_field/name=af_block_form', function (e) {
    var t = e.$el.closest('.acf-block-component');
    a(e.val(), t),
    e.$input().change(function () {
      a(e.val(), t)
    })
  }),

The issue only persists when there are no ACF fields present (dashboard, page overview etc.). I guess the action should be restricted accordingly?

**Comment by fabianlindfors** [comment]
Should be fixed by #99 which will make its way into the next release!
